### ISSUE TITLE
Start了，项目很好，演示试用流畅。为数不多的用户部门多对多的项目。

### ISSUE THREAD

**Issue by sdkfuck** [feiyuchuixue/sz-boot-parent#1]
1.希望有包名，组织名等修改器的类。
2.希望后期能有工作流。
3.希望文件存储可以支持基于数据库的存储。

**Comment by feiyuchuixue** [comment]
## 🙌感谢您的Star支持！
 框架的定位是一款轻量化通用RBAC脚手架，旨在提升开发人员的开发体验。会逐渐增加一些通用性功能，详情可关注官网。

**Comment by feiyuchuixue** [comment]
> 1.希望有包名，组织名等修改器的类。 2.希望后期能有工作流。 3.希望文件存储可以支持基于数据库的存储。

## 🙌感谢您的Star支持！
 框架的定位是一款轻量化通用RBAC脚手架，旨在提升开发人员的开发体验。会逐渐增加一些通用性功能，详情可关注官网。

**Comment by sdkfuck** [comment]
文件配置
![image](https://github.com/feiyuchuixue/sz-boot-parent/assets/86214484/597be929-1ed5-4f90-a222-84bc83904333)

**Comment by sdkfuck** [comment]
![image](https://github.com/feiyuchuixue/sz-boot-parent/assets/86214484/8da80c9a-d2e3-469b-8aa2-9710e91c4030)
请问这个是误提交的么

**Comment by feiyuchuixue** [comment]
> ![image](https://private-user-images.githubusercontent.com/86214484/341250795-8da80c9a-d2e3-469b-8aa2-9710e91c4030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTI0NjAsIm5iZiI6MTcxODg1MjE2MCwicGF0aCI6Ii84NjIxNDQ4NC8zNDEyNTA3OTUtOGRhODBjOWEtZDJlMy00NjliLThhYTItOTcxMGU5MWM0MDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAyNTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwYTJkNjFjYmNlNTA3OGNlZjM3ZGIwMDNmMmE4NTY5NmQ1ZmFhNzkxMGY3NzIyYTcwMWYyZGJlYmJkNjhjZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ETs5F_pMGDHrDrPYWd-kKaGjF6C20qBWNNHDDUqYzU0) 请问这个是误提交的么

这个文件确实不应该提交到仓库上。应该被忽略，后续版本会删除。

**Comment by feiyuchuixue** [comment]
> 文件配置 ![image](https://private-user-images.githubusercontent.com/86214484/341250573-597be929-1ed5-4f90-a222-84bc83904333.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTMxOTQsIm5iZiI6MTcxODg1Mjg5NCwicGF0aCI6Ii84NjIxNDQ4NC8zNDEyNTA1NzMtNTk3YmU5MjktMWVkNS00ZjkwLWEyMjItODRiYzgzOTA0MzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAzMDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZTFhYmY2YmYzMDI0Y2VmNjQxNDVjMzU5NjM4NTFmNDQzOGYyMDIzZjliOTYzNGVjZGM1MDQ5ZDE2ZjIyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LJMjTVUVW2kCflH9MY27zqrWQt_bSMOglK-zYPysyrU)

存储暂时只支持minio。以后有可能考虑做个oss模块，提供通用云厂商的接入能力。
