### ISSUE TITLE
GeneratorTableColumnTableDef 和 GeneratorTableTableDef 缺失

### ISSUE THREAD

**Issue by zhangxin1932** [feiyuchuixue/sz-boot-parent#31]
如图所示，这俩类找不到，在历史版本以及最新版本中都没有：
![image](https://github.com/user-attachments/assets/a42708f6-15c1-43cc-b291-212582a6d0f0)

**Comment by feiyuchuixue** [comment]
参照官网文档[常见问题](https://szadmin.cn/md/Help/doc/question.html#%E4%BB%A3%E7%A0%81%E6%8A%A5%E9%94%99-xxxdef%E6%89%BE%E4%B8%8D%E5%88%B0%E6%80%8E%E4%B9%88%E5%8A%9E)
