### ISSUE TITLE
【字典】别名设置无效的问题（实际也是代码生成的问题）

### ISSUE THREAD

**Issue by mllt992** [feiyuchuixue/sz-boot-parent#40]
## 问题

例如我要给“活动状态”设置一个字典  0代表未发布   1代表已发布 2代表已结束……

如下图

![image](https://github.com/user-attachments/assets/b3e15cce-1035-4b51-9497-33f7a2b890db)

但是实际上提交，别名并没有生效，依旧是提交的编号

![image](https://github.com/user-attachments/assets/c792ffba-564f-4554-ba88-1611eae37931)

我尝试退出重新登录、Ctrl+F5刷新，提交的数据依旧是编号。

## 建议

希望设置了别名的时候，将别名作为key

![image](https://github.com/user-attachments/assets/a677a15c-3d76-45cc-bb90-a45af7e82725)

![image](https://github.com/user-attachments/assets/56247842-4f2d-446e-84da-c9c266e43790)

**Comment by mllt992** [comment]
![image](https://github.com/user-attachments/assets/bf644e15-191a-47cf-ad8e-35674d75323c)

如果要做这样的更改的话，在显示时，也应该判断是否设置了别名，有别名的有别名来匹配，而不是id

**Comment by feiyuchuixue** [comment]
嗯，这里别名目前是需要手动调整代码的。 后续代码生成提供一个配置项，可通过配置项来 启用/关闭 别名的字典映射。

**Comment by feiyuchuixue** [comment]
v0.8.2版本发布
